name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}   # ditt Docker Hub-användarnamn
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }} # Docker Hub token

    - name: Build Docker image
      run: docker build -t mantriesdocker/docker-webapp:latest .

    - name: Push Docker image
      run: docker push mantriesdocker/docker-webapp:latest

    - name: Deploy to Azure VM
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.AZURE_VM_IP }}
        username: ${{ secrets.AZURE_VM_USER }}
        key: ${{ secrets.AZURE_VM_SSH_KEY }}
        script: |
          docker pull mantriesdocker/docker-webapp:latest
          docker stop webapp || true
          docker rm webapp || true
          docker run -d -p 8000:8000 --name webapp mantriesdocker/docker-webapp:latest
