name: Bygg och pusha Docker-image

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: 🛒 Klona repo
        uses: actions/checkout@v3

      - name: 🐳 Logga in på Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: 🔨 Bygg Docker-image
        run: |
          docker build -t mantriesdocker/php-nginx-app:latest .

      - name: 📤 Pusha till Docker Hub
        run: |
          docker push mantriesdocker/php-nginx-app:latest

      - name: 🚀 Deploya till server
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.AZURE_VM_IP }}
          username: ${{ secrets.AZURE_VM_USER }}
          key: ${{ secrets.AZURE_VM_SSH_KEY }}
          script: |
            cd /home/azureuser/docker-app || true

            # Hämta senaste image
            sudo docker pull mantriesdocker/php-nginx-app:latest

            # Stoppa och ta bort gammal container
            sudo docker stop webapp || true
            sudo docker rm webapp || true

            # Starta ny container
            sudo docker run -d --pull always -p 8000:8000 --name webapp mantriesdocker/php-nginx-app:latest

